### ISSUE TITLE
Get value of the input range

### ISSUE THREAD

**Issue by gregory-yet** [dahjson/bubble-slider#1]
Hey nice style, but the script generate a HTML code without any data (i think, i don't search a lot), so we can't get any change on the slider on jQuery. At least i can't get the value like that : 

```javascript
$('.bubble-slider-bubble').text();
```

Can you update the value on input attr "value", this could be nicer.

Thanks for reading !

**Comment by dahjson** [comment]
Sorry, you're having trouble, but the plugin already works this way. It behaves like a normal input field, so you don't have to do anything special when submitting a form to get the value.

However, if your input field had an ID of _example_ you could grab the value like this:

```javascript
$('#example').val();
```

**Comment by gregory-yet** [comment]
When i attempt to get value of my input, this return the default value i have set in .html not the updated value, maybe i'm doing a mistake.

Thank's for your help !

**Comment by dahjson** [comment]
What's the OS, browser, and jQuery versions you're using? Also take a look at the demo page and using the console type:

```javascript
$('#example-1').val();
```

Then move the first example bubble slider to change the value, and type the same thing into the console. Let me know what if it returns the updated value.

**Comment by gregory-yet** [comment]
It works, i was doing a mistake, my bad. Thanks for this nice plugin btw !
